# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignUp():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signUp(self):
    self.driver.get("https://www.xfreehd.com/")
    self.driver.set_window_size(954, 1095)
    self.driver.find_element(By.CSS_SELECTOR, ".modal-content > .modal-footer > .btn").click()
    self.driver.find_element(By.LINK_TEXT, "Sign Up").click()
    self.driver.find_element(By.ID, "signup_username").click()
    self.driver.find_element(By.ID, "signup_username").send_keys("wehaaaasdfg1234")
    self.driver.find_element(By.ID, "signup_password").send_keys("earning$$")
    self.driver.find_element(By.ID, "signup_password_confirm").send_keys("earning$$")
    self.driver.find_element(By.ID, "signup_email").send_keys("ganduramxxxx1234@gmail.com")
    self.driver.find_element(By.ID, "signup_gender_male").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.ID, "signup_age").click()
    self.driver.find_element(By.ID, "signup_certify").click()
    time.sleep(10)

    self.driver.find_element(By.NAME, "submit_signup").click()
  